name: Lock merge queue state
runs:
  using: composite
  steps:
    - name: Checkout merge-queue-state branch
      uses: actions/checkout@v4
      with:
        ref: merge-queue-state
  steps:
    - name: Create lock
      run: |
        for i in {1..10}; do
          if git ls-tree --name-only merge-queue-state lock | grep -q 'lock'; then
            echo "State is locked"
          else
            git config --global user.email "queue_bot@jakeprime.com"
            git config --global user.name "Q-bot"

            touch lock
            git add lock
            git commit -m "Locking merge queue state"
            git push origin HEAD:merge-queue-state
            exit 0
          fi

          sleep 5
        end

        echo "Failed to get lock on merge state"
        exit 1
