name: Merge-Queue
run-name: Merge-Queue

on:
  issue_comment:
    types: [created, edited]

jobs:
  merge:
    if: github.event.issue.pull_request && github.event.comment.body == '/merge'
    name: Merge
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Acknowledge
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.reactions.createForIssueComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              comment_id: ${{ github.event.comment.id }},
              content: 'eyes'
            });

      - uses: jakeprime/merge-queue@ruby
        env:
          COMMENT_ID: ${{ github.event.comment.id }}
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          PR_NUMBER: ${{ github.event.issue.number }}
