name: Merge-Queue
run-name: Merge-Queue

on:
  issue_comment:
    types: [created, edited]

jobs:
  merge:
    if: github.event.issue.pull_request && github.event.comment.body == '/merge'
    name: Merge
    uses: jakeprime/merge-queue/.github/workflows/merge-queue.yml@retry-failures
    permissions: write-all
    secrets: inherit
