name: Merge-Queue
run-name: Merge-Queue

on:
  issue_comment:
    types: [created, edited]

jobs:
  merge:
    if: github.event.issue.pull_request && github.event.comment.body == '/merge'
    name: Merge
    runs-on: ubuntu-latest
    steps:
      - uses: jakeprime/merge-queue@ruby
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        id: greet
        with:
          name: 'Jake'
          loud: 'true'

      - name: Print the timestamp
        run: echo "Ran at ${{ steps.greet.outputs.timestamp }}"
